#!/usr/bin/env bash
# Mac side: launch the FAIL-SAFE simulator wired to the Pi's micro-ROS agent
# over FastDDS. Mirrors ../../scripts/bringup_mac.sh (the parent project's
# bringup) — same conda env, same DDS XML, same Pi preflight — only the
# final exec line runs `drawingrobot_failsafe` instead of `drawingrobot`.
#
# The fail-safe shares /robot/mode_cmd and /cmd_vel topics with the parent,
# so no Pi-side reconfiguration is needed.
#
# Usage:
#   ./scripts/bringup_mac.sh                            # default: open GUI sim
#   ./scripts/bringup_mac.sh --headless --script square
#   ./scripts/bringup_mac.sh --pi-service               # run the fail-safe Pi daemon locally
#
# Env overrides:
#   PI_HOST       — default pi5@192.168.50.53 (used for the SSH preflight AND
#                   as the FastDDS unicast peer, unless PI_DDS_IP is set)
#   PI_DDS_IP     — Pi IP for the FastDDS initialPeersList (default: host part
#                   of PI_HOST). Set this if the Pi's DDS address differs from
#                   its SSH address.
#   MAC_IFACE     — network interface to pin (default: en0, with default-route
#                   fallback). The whitelist address is read from this iface.
#   CONDA_ENV     — default ros2
#   CONDA_ROOT    — default ~/radioconda (auto-detect fallback)
#   SKIP_PI_CHECK — set to 1 to skip the SSH preflight (e.g. when offline)
set -euo pipefail

PI_HOST="${PI_HOST:-pi5@192.168.50.53}"
PI_DDS_IP="${PI_DDS_IP:-${PI_HOST##*@}}"   # strip user@ → bare IP/host
MAC_IFACE="${MAC_IFACE:-en0}"
CONDA_ENV="${CONDA_ENV:-ros2}"

cd "$(dirname "$0")/.."
FAILSAFE_DIR="$(pwd)"
# We GENERATE the FastDDS profile at launch (see below) with the Mac's
# *current* interface IP, because a hardcoded whitelist address goes stale
# every time DHCP hands out a new lease — and a stale whitelist makes
# FastDDS filter out every interface ("All whitelist interfaces were
# filtered out"), silently killing all outbound traffic. The committed
# parent XML is kept only as a human-readable reference.
PARENT_REPO="$(cd .. && pwd)"
DDS_XML_TEMPLATE="$PARENT_REPO/scripts/dds/fastdds-mac.xml"
DDS_XML="${TMPDIR:-/tmp}/fastdds-mac-${USER:-drawingrobot}.generated.xml"

say() { printf '\n=== %s ===\n' "$*"; }
fail() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

# --- Preflight -----------------------------------------------------------

say "preflight"

[ -f "$DDS_XML_TEMPLATE" ] || \
    fail "missing $DDS_XML_TEMPLATE (expected the parent project's DDS profile reference)"

# Detect the Mac's current LAN IP. Try MAC_IFACE first, then the interface
# that owns the default route (covers Macs where WiFi is en1, not en0).
MAC_IP="$(ipconfig getifaddr "$MAC_IFACE" 2>/dev/null || true)"
if [ -z "$MAC_IP" ]; then
    DEF_IF="$(route -n get default 2>/dev/null | awk '/interface:/{print $2}')"
    if [ -n "$DEF_IF" ]; then
        MAC_IP="$(ipconfig getifaddr "$DEF_IF" 2>/dev/null || true)"
        [ -n "$MAC_IP" ] && MAC_IFACE="$DEF_IF"
    fi
fi
[ -n "$MAC_IP" ] || fail "could not determine this Mac's LAN IP (tried iface '$MAC_IFACE' and the default route). Set MAC_IFACE=enX."
echo "OK Mac DDS interface: $MAC_IFACE = $MAC_IP"
echo "OK Pi DDS peer: $PI_DDS_IP"

# Generate the FastDDS profile with the detected whitelist IP + Pi peer.
# transport_descriptors MUST come before <participant> (FastDDS parses in
# document order; a participant referencing an undefined transport silently
# rejects the whole profile). See parent CLAUDE.md.
cat > "$DDS_XML" <<XML
<?xml version="1.0" encoding="UTF-8" ?>
<!-- AUTO-GENERATED by bringup_mac.sh. Do not edit; edit the script's heredoc.
     whitelist=$MAC_IP ($MAC_IFACE)  peer=$PI_DDS_IP -->
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
  <transport_descriptors>
    <transport_descriptor>
      <transport_id>udpv4_pinned</transport_id>
      <type>UDPv4</type>
      <interfaceWhiteList>
        <address>$MAC_IP</address>
      </interfaceWhiteList>
    </transport_descriptor>
  </transport_descriptors>

  <participant profile_name="default_participant" is_default_profile="true">
    <rtps>
      <builtin>
        <initialPeersList>
          <locator>
            <udpv4>
              <address>$PI_DDS_IP</address>
            </udpv4>
          </locator>
        </initialPeersList>
      </builtin>
      <userTransports>
        <transport_id>udpv4_pinned</transport_id>
      </userTransports>
      <useBuiltinTransports>false</useBuiltinTransports>
    </rtps>
  </participant>
</profiles>
XML
echo "OK generated DDS profile: $DDS_XML"

CONDA_ROOT="${CONDA_ROOT:-$HOME/radioconda}"
if [ ! -f "$CONDA_ROOT/etc/profile.d/conda.sh" ]; then
    for candidate in "$HOME/miniforge3" "$HOME/miniconda3" "$HOME/anaconda3" "/opt/homebrew/Caskroom/miniconda/base"; do
        if [ -f "$candidate/etc/profile.d/conda.sh" ]; then
            CONDA_ROOT="$candidate"
            break
        fi
    done
fi
[ -f "$CONDA_ROOT/etc/profile.d/conda.sh" ] || \
    fail "conda not found (tried $CONDA_ROOT). Set CONDA_ROOT=/path/to/your/conda"
# shellcheck disable=SC1091
source "$CONDA_ROOT/etc/profile.d/conda.sh"

if ! conda env list | awk '{print $1}' | grep -Fxq "$CONDA_ENV"; then
    fail "conda env '$CONDA_ENV' not found. See parent project's CLAUDE.md for RoboStack install."
fi
echo "OK conda env: $CONDA_ENV"

if [ "${SKIP_PI_CHECK:-0}" != "1" ]; then
    if ssh -o BatchMode=yes -o ConnectTimeout=4 "$PI_HOST" true 2>/dev/null; then
        if ssh "$PI_HOST" 'sudo docker ps --format "{{.Names}}" 2>/dev/null | grep -Fxq micro_ros_agent' 2>/dev/null; then
            echo "OK Pi reachable at $PI_HOST, micro_ros_agent container is up"
        else
            echo "WARN Pi reachable but micro_ros_agent container is not running."
            echo "     ssh $PI_HOST then 'cd ~/Documentos/Luloc-ASTI-25-26/02-software && docker compose up -d'"
        fi
    else
        echo "WARN cannot ssh to $PI_HOST (set SKIP_PI_CHECK=1 to silence) — continuing anyway"
    fi
fi

# --- Mac DDS env + run fail-safe ----------------------------------------

say "starting fail-safe simulator (Ctrl-C to stop)"

set +u
conda activate "$CONDA_ENV"
set -u

# Export AFTER conda activate — RoboStack's activate.d overrides RMW_IMPLEMENTATION
# with the env default; exporting before activation gets clobbered.
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
export ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-0}"
export FASTRTPS_DEFAULT_PROFILES_FILE="$DDS_XML"
unset CYCLONEDDS_URI

# Run from the fail_safe dir so the relative pi_slots.json / scripts/ paths
# resolve correctly.
cd "$FAILSAFE_DIR"
exec python -m drawingrobot_failsafe --ros "$@"
